apiVersion: v1
kind: ConfigMap
metadata:
  name: lifeai-config
  namespace: lifeai
data:
  # Banco de dados
  DB_ENGINE: "django.db.backends.postgresql_psycopg2"
  DB_HOST: "postgres-service"
  DB_NAME: "lifeAI"
  DB_PORT: "5432"

  # App settings
  FRONT_HOST: "http://localhost:90"
  GEMINI_API_KEY: "REPLACE_WITH_YOUR_GEMINI_API_KEY"
  
  LM_API_URL: "http://127.0.0.1:1234/v1/chat/completions"
  LM_API_MODEL: "meta-llama-3-8b-instruct"

  DEBUG: "False"
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp-relay.brevo.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST_USER: "9b1ae8001@smtp-brevo.com"
  DEFAULT_FROM_EMAIL: "contatolifeai@gmail.com"