apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - django-api/
  - postgres/
  - pgadmin/
  - ingress.yaml
  - roles.yaml
  - rolebindings.yaml
  # - serviceaccounts.yaml

secretGenerator:
- name: lifeai-secrets
  namespace: lifeai
  behavior: replace
  envs:
    - secrets.env
